### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by z3ntu** [comment]
Is there any reference what the difference between the two runtimes are (other than looking at the commit log)? Apparently nothing really changed in the runtime-version-communication since 2018 (see https://github.com/flathub/xyz.z3ntu.razergenie/issues/1#issuecomment-405717412) :(

**Comment by travier** [comment]
The difference is that the 5.15-21.08 KDE Runtime is based on the 21.08 Freedesktop Runtime whereas the 5.15 one is stuck on the 20.08 one for compatibility. Everything else in Qt/KDE should be mostly the same.

**Comment by travier** [comment]
See https://invent.kde.org/packaging/flatpak-kde-runtime/-/tree/qt5.15lts-21.08

**Comment by hfiguiere** [comment]
which mean that next August you won't get the message the runtime is EOL.

**Pull request merged**
